// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2HDQwbgRzK6pxuzFmHkPvHWQeAH4Pec',
    appId: '1:232479975507:web:be6b692d7463849573fea6',
    messagingSenderId: '232479975507',
    projectId: 'furniture-ef43b',
    authDomain: 'furniture-ef43b.firebaseapp.com',
    databaseURL: 'https://furniture-ef43b-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-ef43b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7oUROpB1fFDAZnxUPAyDNAyrwB03bpzI',
    appId: '1:232479975507:android:1c62b438fa31d69c73fea6',
    messagingSenderId: '232479975507',
    projectId: 'furniture-ef43b',
    databaseURL: 'https://furniture-ef43b-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-ef43b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT0ympmWHcWNJklBdoLaOAfR5UVLg2nQ0',
    appId: '1:232479975507:ios:d713bf3fdc6cf87073fea6',
    messagingSenderId: '232479975507',
    projectId: 'furniture-ef43b',
    databaseURL: 'https://furniture-ef43b-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-ef43b.appspot.com',
    iosBundleId: 'com.example.furnitureHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT0ympmWHcWNJklBdoLaOAfR5UVLg2nQ0',
    appId: '1:232479975507:ios:d713bf3fdc6cf87073fea6',
    messagingSenderId: '232479975507',
    projectId: 'furniture-ef43b',
    databaseURL: 'https://furniture-ef43b-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-ef43b.appspot.com',
    iosBundleId: 'com.example.furnitureHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG2HDQwbgRzK6pxuzFmHkPvHWQeAH4Pec',
    appId: '1:232479975507:web:2d56b54d2151287173fea6',
    messagingSenderId: '232479975507',
    projectId: 'furniture-ef43b',
    authDomain: 'furniture-ef43b.firebaseapp.com',
    databaseURL: 'https://furniture-ef43b-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-ef43b.appspot.com',
  );
}
